apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: benjiegonzalez/practica4:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: TITLE
          value: "HOLA MUNDO 3"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SECRET
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_PASSWORD 
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_HOST
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_DB
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000   