version: '3'
services:
  # Servicio para el cliente Angular
  client:
    build:
      context: ./client
    ports:
      - "80:80"

  # Servicio para el servidor Node.js
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_MONGO=mongodb://mongo:27017/cbm

  # Servicio para MongoDB
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null

  # Servicio para Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
