export enum RabbitMQ {
  DepartamentoUsuarioQueue = 'departamentoUsuarios',
}

export enum DepartamentoUsuarioMSG {
  CREATE = 'CREATE_DEPARTAMENTO_USUARIO',
  FIND_ALL = 'FIND_DEPARTAMENTO_USUARIOS',
  FIND_ONE = 'FIND_DEPARTAMENTO_USUARIO',
  UPDATE = 'UPDATE_DEPARTAMENTO_USUARIO',
  DELETE = 'DELETE_DEPARTAMENTO_USUARIO',
}
