apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jofre159rz/nestjs-repository:nestjs
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_HOST
          value: "cluster0.ezxkxg9.mongodb.net"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_USERNAME

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: MONGO_PASSWORD

        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort

  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # cualquier puerto
      targetPort: 3000      