apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  # Base64 String:  postgres = cG9zdGdyZXM=
  # echo -n postgres | base64
  MONGO_USERNAME: ampyejExMzUwNTE3MTA=
  # EstoEsUnPassWordSecreto
  MONGO_PASSWORD: MTM1MDUxNzE3MQ==
